### ISSUE TITLE
Delete method not sending signals

### ISSUE THREAD

**Issue by mohaali482** [xgeekshq/django-timestamps#5]
When deleting an object it would be nice if it sends signals

**Comment by arkady-truelogic** [comment]
@dmp593 this issue is because you are not using `Collector` from django. This class is responsible to emit the signals.

Maybe the best approach is implement a `timestamps.models.collectors.SoftCollector` and (using as reference `django.db.models.deletion.Collector`) and use on the model:
```
def delete(self, using=None, keep_parents=False):
        if self.pk is None:
            raise ValueError(
                "%s object can't be deleted because its %s attribute is set "
                "to None." % (self._meta.object_name, self._meta.pk.attname)
            )
        using = using or router.db_for_write(self.__class__, instance=self)
        collector = SoftCollector(using=using, origin=self)
        collector.collect([self], keep_parents=keep_parents)
        return collector.delete()
        
def restore(self, using=None, keep_parents=False):
        if self.pk is None:
            raise ValueError(
                "%s object can't be deleted because its %s attribute is set "
                "to None." % (self._meta.object_name, self._meta.pk.attname)
            )
        using = using or router.db_for_write(self.__class__, instance=self)
        collector = SoftCollector(using=using, origin=self)
        collector.collect([self], keep_parents=keep_parents)
        return collector.restore()
```

**Comment by dmp593** [comment]
Hello @mohaali482 and @arkady-truelogic.
First of all, thank you both for the contribution. 😊
Secondly, I'm really sorry for the delay in addressing this.

@mohaali482 Regarding sending signals when soft deleting (as well as when restoring), you can use the default Django signal (pre_save/post_save) since soft deleting is just setting the "deleted_at" attribute with the value of timezone.utc() and when restoring it puts the deleted_at back to null again. 

If we check the [documentation](https://docs.djangoproject.com/en/4.1/ref/signals/#module-django.db.models.signals) I think that we can look into the "updated_fields" array to understand if the property "deleted_at" was updated.

But either way, that seemed a good improvement to add! 💯 

Sometimes you only want to listen to the deleted/restored event without the need to do if/else conditions based on the presence or the absence of the field "deleted_at" in the updated_fields array.

Because of that, I'm currently working on the issue. It's still a work in progress, but you can check pull request #7.

Finally, also thank @arkady-truelogic for the suggestion, but I think that in this case the use of a collector is not applicable since a soft delete or a restore operation are, in fact, operations of update. Either way, please check PR #7 and give your insight. 😎

Again, thank you both! 🤩
